config/routes.rb
Rails.application.routes.draw do
  resources :secrets

  get 'welcome/index'

  root 'welcome#index'

  devise_for :users

end

app/models/secret.rb
class Secret < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :secrets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :age, :location, :favorite_flavor) }
    devise_parameter_sanitizer.permit(:account_update) { |u| 
      u.permit(:email, :password, :password_confirmation, :current_password, :name, :age, :location, :favorite_flavor) 
    }
	end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :set_secret, only: [:show, :edit, :update, :destroy]

  # GET /secrets
  # GET /secrets.json
  def index
    @secrets = Secret.all
  end

  # GET /secrets/1
  # GET /secrets/1.json
  def show
  end

  # GET /secrets/new
  def new
    @secret = Secret.new
  end

  # GET /secrets/1/edit
  def edit
  end

  # POST /secrets
  # POST /secrets.json
  def create
    @secret = Secret.new(secret_params)

    @secret.user_id = current_user.id

    respond_to do |format|
      if @secret.save
        format.html { redirect_to root_path, notice: 'Secret was successfully created.' }
        format.json { render action: 'show', status: :created, location: @secret }
      else
        format.html { render :new }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secrets/1
  # PATCH/PUT /secrets/1.json
  def update
    respond_to do |format|
      if @secret.update(secret_params)
        format.html { redirect_to @secret, notice: 'Secret was successfully updated.' }
        format.json { render :show, status: :ok, location: @secret }
      else
        format.html { render :edit }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secrets/1
  # DELETE /secrets/1.json
  def destroy
    @secret.destroy
    respond_to do |format|
      format.html { redirect_to secrets_url, notice: 'Secret was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secret
      @secret = Secret.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secret_params
      params.require(:secret).permit(:secret_message, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labfour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<%= form_for(@secret) do |f| %>
  <% if @secret.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secret.errors.count, "error") %> prohibited this secret from being saved:</h2>

      <ul>
      <% @secret.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :secret_message %><br>
    <%= f.text_field :secret_message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secrets/edit.html.erb
<h1>Editing secret</h1>

<%= render 'form' %>

<%= link_to 'Show', @secret %> |
<%= link_to 'Back', secrets_path %>

app/views/secrets/index.html.erb
<h1>Listing secrets</h1>

<table>
  <thead>
    <tr>
      <th>Secret message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secrets.each do |secret| %>
      <tr>
        <td><%= secret.secret_message %></td>
        <td><%= secret.user_id %></td>
        <td><%= link_to 'Show', secret %></td>
        <td><%= link_to 'Edit', edit_secret_path(secret) %></td>
        <td><%= link_to 'Destroy', secret, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secret', new_secret_path %>

app/views/secrets/new.html.erb
<h1>New secret</h1>

<%= render 'form' %>

<%= link_to 'Back', secrets_path %>

app/views/secrets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Secret message:</strong>
  <%= @secret.secret_message %>
</p>

<p>
  <strong>User:</strong>
  <%= @secret.user_id %>
</p>

<%= link_to 'Edit', edit_secret_path(@secret) %> |
<%= link_to 'Back', secrets_path %>

app/views/welcome/index.html.erb
<div id="fancy" name="fancy">
	<a href="javascript:showSecret(1);">Reveal</a>
</div>

<% if user_signed_in? %>
	<h2>Let's Practice jQuery and AJAX</h2>
	<div class="container">
	<% @users.each do |user| %>
		<div class="col-md-3">
			<div class="name" id="clickname_<%= user.id %>"><%= user.name %></div>
			<div class="user-info" id="toggleinfo_<%= user.id %>">
				<p>Age: <%= user.age %></p>
				<p>Location: <%= user.location %></p>
				<p>Favorite Flavor: <%= user.favorite_flavor %></p> 
					<% if user.secrets.empty? && user.id == current_user.id %>
						<p><%= link_to "Enter Your Secret Message Now!", new_secret_path %></p>
					<% else %>
						<p>Secret: <span id="secret_msg_<%= user.id %>"><a href="javascript:showSecret(<%= user.id %>);">Reveal</a></span></p>
					<% end %>
			</div>
		</div>
	<% end %>
	</div>

	<div>
		<%= link_to "Sign out",destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
	</div>

<% else %>

	<div class="container">
		<div class="col-md-5 sign-in-boxes">
			<h3>Sign In:</h3><br />
			<%= form_for(:user, :url => session_path(:user)) do |f| %>
			  <p><strong>Email:</strong> <%= f.text_field :email %></p>
			  <p><strong>Password:</strong> <%= f.password_field :password %></p>
			  <p><%= f.check_box :remember_me %> <%= f.label :remember_me %></p>
			  <p><%= f.submit 'Sign In' %></p>
			  <p><%= link_to "Forgot your password?", new_password_path(:user) %></p>
			<% end %>
		</div>
		<div class="col-md-2"></div>
		<div class="col-md-5 sign-in-boxes">
			<h3>Not yet registered?</h3><br />
			<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
			  <%= devise_error_messages! %>

			  <p><%= f.label :email %><br />
			  <%= f.email_field :email, autofocus: true %></p>

			  <p><%= f.label :name %><br />
			  <%= f.text_field :name %></p>

			  <p><%= f.label :age %><br />
			  <%= f.number_field :age %></p>

			  <p><%= f.label :location %><br />
  			<%= f.text_field :location %></p>

  			<p><%= f.label :favorite_flavor %><br />
  			<%= f.text_field :favorite_flavor %></p>

			  <p><%= f.label :password %><br />
			    <%= f.password_field :password, autocomplete: "off" %></p>

			  <p><%= f.label :password_confirmation %><br />
			    <%= f.password_field :password_confirmation, autocomplete: "off" %></p>

			  <div><%= f.submit "Sign Up" %></div>
			<% end %>	
		</div>
	</div>
<% end %>

<script>

</script>